### ISSUE TITLE
parse-android-dynparts missing from prebuilt rootfs

### ISSUE THREAD

**Issue by Rouji** [m-weigand/pinenote-debian-recipes#13]
https://github.com/m-weigand/pinenote-debian-recipes/releases/download/v20221031/debian_bookworm_arm64_pinenote_v20221031.tar.gz doesn't contain `/root/parse-android-dynparts`. 
Not really sure why; I had a look at the code and didn't see anything obvious. 
Had a go at building locally as well, but had nothing but problems with debos/debootstrap and kind of ran out of time :/

**Comment by m-weigand** [comment]
fixed
