### ISSUE TITLE
Allow for default settings that play nicely with gnome-helper

### ISSUE THREAD

**Issue by not-a-doctor-stromberg** [m-weigand/pinenote-debian-recipes#17]
Hi Maximilian,

My preferred driver settings are:
```
rockchip_ebc.bw_mode=1 rockchip_ebc.default_waveform=1 rockchip_ebc.refresh_threshold=30 rockchip_ebc.auto_refresh=1
```
I tried setting those in `extlinux.conf`, but the bw_mode at least [is overwritten by the gnome helper here](https://github.com/m-weigand/pinenote-debian-recipes/blob/mw_image/overlays/pnhelper%40m-weigand.github.com/extension.js#L440). 

It seems like in other places we read the file first with _get_content ([in _add_auto_refresh_button for example](https://github.com/m-weigand/pinenote-debian-recipes/blob/3ed014bc0db592561f162fd62d8e5cfb3b9f8762/overlays/pnhelper%40m-weigand.github.com/extension.js#L330)) -- I will try doing something similar for changing bw mode (and will try to clean up the spacing as well).

Let me know if you disagree with this approach. I am planning on issuing a pull request for this, but if someone beats me to it, no problamo :)

**Comment by m-weigand** [comment]
Hi,
thanks for bringing up this issue - indeed parameters should not be overwritten by the gnome extension.

It would be nice if you could use this location for drafting your merge request, as the recipes repo only holds a copy of the gnome extensions. Also note that managing of ebc parameters will be outsourced to the dbus daemon (see linked branch below).

https://github.com/m-weigand/mw_pinenote_misc/tree/dbus_integration/gnome_extension

Thanks again!

**Comment by not-a-doctor-stromberg** [comment]
Closing in favor of: https://github.com/m-weigand/mw_pinenote_misc/issues/5
